spring:
  profiles:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/techlect
    username: sa
    password:
  jpa:
    show-sql: true

logging:
  level:
    io.zingoworks.techlect: DEBUG
    org.springframework: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
